package terminal

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/gorilla/websocket"
	"golang.org/x/crypto/ssh"

	"github.com/labtether/labtether/internal/hubapi/shared"
	"github.com/labtether/labtether/internal/terminal"
)

const (
	SSHDialAttemptTimeout  = 6 * time.Second
	SSHDialMaxAttempts     = 2
	SSHDialRetryDelay      = 350 * time.Millisecond
	SSHShellStartupTimeout = 8 * time.Second
)

// HandleSSHTerminalStream handles terminal streaming via direct SSH connection.
func (d *Deps) HandleSSHTerminalStream(w http.ResponseWriter, r *http.Request, session terminal.Session) {
	traceID := shared.BrowserStreamTraceID(r)
	traceLog := shared.StreamTraceLogValue(traceID)
	logContext := fmt.Sprintf("session=%s target=%s trace=%s", session.ID, session.Target, traceLog)

	wsConn, err := d.TerminalWebSocketUpgrader.Upgrade(w, r, nil)
	if err != nil {
		log.Printf("terminal-ssh: upgrade_failed %s err=%v", logContext, err) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local upgrade errors.
		return
	}
	defer wsConn.Close()
	wsConn.SetReadLimit(maxTerminalInputReadBytes)

	// Concurrent session registry: evict any previous WebSocket for this
	// persistent session before registering the new one.
	persistentSessionID := strings.TrimSpace(session.PersistentSessionID)
	if persistentSessionID != "" {
		if prev, loaded := d.ActivePersistentConns.LoadAndDelete(persistentSessionID); loaded {
			if prevConn, ok := prev.(*websocket.Conn); ok {
				_ = prevConn.WriteControl(
					websocket.CloseMessage,
					websocket.FormatCloseMessage(websocket.CloseNormalClosure, "session attached elsewhere"),
					time.Now().Add(2*time.Second),
				)
				_ = prevConn.Close()
				log.Printf("terminal-ssh: evicted_previous_conn persistent_session=%s %s", persistentSessionID, logContext) // #nosec G706 -- Log values are bounded session identifiers generated by the hub.
			}
		}
		d.ActivePersistentConns.Store(persistentSessionID, wsConn)
		defer d.ActivePersistentConns.CompareAndDelete(persistentSessionID, wsConn)
	}

	resolved, err := d.ResolveSessionSSHConfig(session)
	if err != nil {
		log.Printf("terminal-ssh: stream_setup_failed reason=ssh_config_invalid %s err=%v", logContext, err) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local validation errors.
		_ = WriteTerminalError(wsConn, "ssh_config_invalid", fmt.Sprintf("Terminal stream unavailable: %v", err))
		return
	}
	if resolved == nil {
		log.Printf("terminal-ssh: stream_setup_failed reason=ssh_config_missing %s", logContext) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
		_ = WriteTerminalError(wsConn, "ssh_config_missing",
			"Terminal unavailable: no agent connected and no SSH credentials configured. Deploy the LabTether Agent on this device, or set SSH_USERNAME + SSH_PASSWORD/SSH_PRIVATE_KEY.")
		return
	}

	clientConfig, err := d.CreateSSHClientConfig(resolved, SSHDialAttemptTimeout)
	if err != nil {
		log.Printf("terminal-ssh: stream_setup_failed reason=ssh_client_config_invalid %s err=%v", logContext, err) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local validation errors.
		_ = WriteTerminalError(wsConn, "ssh_config_invalid", fmt.Sprintf("Invalid SSH config: %v", err))
		return
	}

	addr := net.JoinHostPort(resolved.Host, strconv.Itoa(resolved.Port))
	connectStart := time.Now()

	// Track intermediate SSH clients from jump chain dialing for cleanup.
	var intermediateClients []*ssh.Client
	defer func() {
		CloseIntermediateClients(intermediateClients)
	}()

	var sshClient *ssh.Client
	var attemptsUsed int

	// Resolve jump chain if available — dial through hops instead of direct.
	jumpChainUsed := false
	{
		groupID, groupErr := d.GetAssetGroupID(session.Target)
		if groupErr != nil {
			log.Printf("terminal-ssh: jump_chain_skip reason=group_lookup_failed %s err=%v", logContext, groupErr) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
		} else if groupID != "" {
			hops, hopErr := d.ResolveJumpChain(groupID)
			if hopErr != nil {
				log.Printf("terminal-ssh: jump_chain_skip reason=resolve_failed group=%s %s err=%v", groupID, logContext, hopErr) // #nosec G706 -- Group and session identifiers are hub-controlled values.
			} else if len(hops) > 0 {
				_ = WriteTerminalHopProgress(wsConn, 0, len(hops), "",
					fmt.Sprintf("Connecting through %d-hop jump chain...", len(hops)))

				target := terminal.ResolvedHop{
					Addr:         addr,
					ClientConfig: clientConfig,
				}
				chainClient, intermediates, chainErr := DialSSHChain(hops, target,
					func(hopIndex, hopCount int, hopHost string) {
						_ = WriteTerminalHopProgress(wsConn, hopIndex+1, hopCount, hopHost,
							fmt.Sprintf("Hop %d/%d connected (%s)", hopIndex+1, hopCount, hopHost))
					},
					time.Sleep,
				)
				if chainErr != nil {
					log.Printf("terminal-ssh: stream_setup_failed reason=jump_chain_failed %s err=%v", logContext, chainErr) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local connection errors.
					_ = WriteTerminalError(wsConn, "ssh_connect_failed",
						fmt.Sprintf("SSH jump chain connection failed: %v", chainErr))
					return
				}
				sshClient = chainClient
				intermediateClients = intermediates
				attemptsUsed = 1
				jumpChainUsed = true
				log.Printf("terminal-ssh: jump_chain_connected hops=%d %s", len(hops), logContext) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
			}
		}
	}

	// Fall back to direct dial if no jump chain was used.
	if !jumpChainUsed {
		var dialErr error
		sshClient, attemptsUsed, dialErr = DialSSHWithRetry(
			addr,
			clientConfig,
			SSHDialAttemptTimeout,
			SSHDialMaxAttempts,
			SSHDialRetryDelay,
			func(network, target string, cfg *ssh.ClientConfig) (*ssh.Client, error) {
				return ssh.Dial(network, target, cfg)
			},
			time.Sleep,
			func(attempt, attempts int) {
				_ = WriteTerminalStatus(wsConn, "ssh_connecting",
					fmt.Sprintf("Connecting to SSH endpoint (%d/%d)...", attempt, attempts),
					attempt, attempts,
					time.Since(connectStart).Milliseconds(),
				)
			},
		)
		if dialErr != nil {
			log.Printf("terminal-ssh: stream_setup_failed reason=ssh_connect_failed %s attempts=%d err=%v", logContext, attemptsUsed, dialErr) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local connection errors.
			_ = WriteTerminalError(wsConn, "ssh_connect_failed",
				fmt.Sprintf("SSH connection failed after %d attempt(s): %v", attemptsUsed, dialErr),
			)
			return
		}
	}
	defer sshClient.Close()
	_ = WriteTerminalStatus(wsConn, "ssh_starting_shell", "Starting remote shell...", attemptsUsed, SSHDialMaxAttempts, time.Since(connectStart).Milliseconds())

	cols, rows := ParseTerminalSize(r.URL.Query().Get("cols"), r.URL.Query().Get("rows"))
	startCommand := ""
	if tmuxSessionName := strings.TrimSpace(session.TmuxSessionName); tmuxSessionName != "" {
		startCommand = "tmux new-session -A -s " + shared.ShellSingleQuote(tmuxSessionName)
	}
	sshSession, stdin, stdout, stderr, err := StartSSHInteractiveSessionWithTimeout(sshClient, cols, rows, startCommand, SSHShellStartupTimeout)
	if err != nil {
		log.Printf("terminal-ssh: stream_setup_failed reason=ssh_start_failed %s err=%v", logContext, err) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local startup errors.
		_ = WriteTerminalError(wsConn, "ssh_start_failed", err.Error())
		return
	}
	defer sshSession.Close()
	log.Printf("terminal-ssh: stream_connected %s cols=%d rows=%d", logContext, cols, rows) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.

	// --- Scrollback replay on reconnect (best-effort) ---
	if persistentSessionID != "" {
		d.replayScrollbackOnReconnect(wsConn, sshClient, session, logContext)
	}

	_ = WriteTerminalReady(wsConn, "Terminal connected", time.Since(connectStart).Milliseconds())

	var writeMu sync.Mutex
	stopKeepalive := shared.StartBrowserWebSocketKeepalive(wsConn, &writeMu, "terminal-ssh:"+session.ID)
	defer stopKeepalive()

	writeOutput := func(payload []byte) error {
		if len(payload) == 0 {
			return nil
		}
		writeMu.Lock()
		defer writeMu.Unlock()
		return wsConn.WriteMessage(websocket.BinaryMessage, payload)
	}

	// --- TeeWriter: capture stdout to ring buffer for persistent sessions ---
	var ringBuf *terminal.RingBuffer
	var flushCancel context.CancelFunc
	if persistentSessionID != "" && d.TerminalInMemStore != nil {
		ringBuf = d.TerminalInMemStore.GetOrCreateScrollbackBuffer(persistentSessionID)
		var flushCtx context.Context
		flushCtx, flushCancel = context.WithCancel(context.Background())
		go d.scrollbackFlushLoop(flushCtx, persistentSessionID, ringBuf)
	}
	if flushCancel != nil {
		defer flushCancel()
	}

	// Build the output writer: if we have a ring buffer, tee into it.
	var stdoutWriter io.Writer = WriterFunc(writeOutput)
	if ringBuf != nil {
		stdoutWriter = &scrollbackTeeWriter{wsWriter: WriterFunc(writeOutput), ringBuf: ringBuf}
	}

	go func() {
		if _, err := io.Copy(stdoutWriter, stdout); err != nil && !errors.Is(err, io.EOF) {
			log.Printf("terminal-ssh: stream_runtime_event reason=ssh_stdout_copy_failed %s err=%v", logContext, err) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
		}
	}()
	go func() {
		if _, err := io.Copy(stdoutWriter, stderr); err != nil && !errors.Is(err, io.EOF) {
			log.Printf("terminal-ssh: stream_runtime_event reason=ssh_stderr_copy_failed %s err=%v", logContext, err) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
		}
	}()

	endReason := "unknown"
	var endErr error
	for {
		messageType, payload, err := wsConn.ReadMessage()
		if err != nil {
			switch {
			case websocket.IsCloseError(err, websocket.CloseNormalClosure):
				endReason = "browser_ws_closed_normal"
			case websocket.IsCloseError(err, websocket.CloseGoingAway):
				endReason = "browser_ws_closed_going_away"
			default:
				var closeErr *websocket.CloseError
				switch {
				case errors.As(err, &closeErr):
					endReason = fmt.Sprintf("browser_ws_closed_code_%d", closeErr.Code)
				default:
					var netErr net.Error
					if errors.As(err, &netErr) && netErr.Timeout() {
						endReason = "browser_ws_read_timeout"
					} else {
						endReason = "browser_ws_read_error"
					}
				}
				endErr = err
			}
			break
		}
		_ = shared.TouchBrowserWebSocketReadDeadline(wsConn)
		if messageType != websocket.TextMessage && messageType != websocket.BinaryMessage {
			continue
		}
		handled, controlErr := HandleTerminalControlMessage(sshSession, stdin, payload)
		if controlErr != nil {
			endReason = "control_message_error"
			endErr = controlErr
			_ = WriteTerminalError(wsConn, "ssh_control_failed", "Terminal control channel failed")
			break
		}
		if handled {
			continue
		}
		if _, err := stdin.Write(payload); err != nil {
			endReason = "ssh_stdin_write_error"
			endErr = err
			_ = WriteTerminalError(wsConn, "ssh_stdin_failed", "SSH input channel closed")
			break
		}
	}
	// Final flush of ring buffer to Postgres before disconnect.
	if ringBuf != nil && d.TerminalScrollbackStore != nil && persistentSessionID != "" {
		if snap := ringBuf.Snapshot(); len(snap) > 0 {
			_ = d.TerminalScrollbackStore.UpsertScrollback(persistentSessionID, snap, ringBuf.ByteSize(), ringBuf.Lines())
		}
	}

	if endErr != nil {
		log.Printf("terminal-ssh: stream_ended reason=%s %s elapsed=%s err=%v", endReason, logContext, time.Since(connectStart).Round(time.Millisecond), endErr) // #nosec G706 -- Reason and context are bounded runtime values.
	} else {
		log.Printf("terminal-ssh: stream_ended reason=%s %s elapsed=%s", endReason, logContext, time.Since(connectStart).Round(time.Millisecond)) // #nosec G706 -- Reason and context are bounded runtime values.
	}

}

func DialSSHWithRetry(
	addr string,
	baseConfig *ssh.ClientConfig,
	attemptTimeout time.Duration,
	maxAttempts int,
	retryDelay time.Duration,
	dialFn func(network, target string, cfg *ssh.ClientConfig) (*ssh.Client, error),
	sleepFn func(time.Duration),
	onAttempt func(attempt, attempts int),
) (*ssh.Client, int, error) {
	if baseConfig == nil {
		return nil, 0, errors.New("ssh client config is required")
	}
	if maxAttempts <= 0 {
		maxAttempts = 1
	}
	if dialFn == nil {
		return nil, 0, errors.New("ssh dial function is required")
	}
	if sleepFn == nil {
		sleepFn = time.Sleep
	}

	var lastErr error
	for attempt := 1; attempt <= maxAttempts; attempt++ {
		if onAttempt != nil {
			onAttempt(attempt, maxAttempts)
		}
		cfg := *baseConfig
		cfg.Timeout = attemptTimeout
		dialStart := time.Now()
		client, err := dialFn("tcp", addr, &cfg)
		if err == nil && client != nil {
			log.Printf("terminal-ssh: connected to %s on attempt %d/%d in %s", addr, attempt, maxAttempts, time.Since(dialStart).Round(time.Millisecond)) // #nosec G706 -- Address comes from resolved operator config; remaining fields are bounded runtime values.
			return client, attempt, nil
		}
		if err == nil {
			err = errors.New("ssh dial returned nil client")
		}
		lastErr = err
		log.Printf("terminal-ssh: attempt %d/%d to %s failed after %s: %v", attempt, maxAttempts, addr, time.Since(dialStart).Round(time.Millisecond), err) // #nosec G706 -- Address comes from resolved operator config; remaining fields are bounded runtime values.
		if attempt < maxAttempts && retryDelay > 0 {
			sleepFn(retryDelay)
		}
	}
	return nil, maxAttempts, fmt.Errorf("ssh dial failed: %w", lastErr)
}

func StartSSHInteractiveSessionWithTimeout(
	sshClient *ssh.Client,
	cols int,
	rows int,
	startCommand string,
	timeout time.Duration,
) (*ssh.Session, io.WriteCloser, io.Reader, io.Reader, error) {
	if sshClient == nil {
		return nil, nil, nil, nil, errors.New("ssh client is required")
	}

	type sessionInitResult struct {
		session *ssh.Session
		stdin   io.WriteCloser
		stdout  io.Reader
		stderr  io.Reader
		err     error
	}

	resultCh := make(chan sessionInitResult, 1)
	go func() {
		sshSession, err := sshClient.NewSession()
		if err != nil {
			resultCh <- sessionInitResult{err: fmt.Errorf("ssh session failed: %w", err)}
			return
		}

		stdin, err := sshSession.StdinPipe()
		if err != nil {
			_ = sshSession.Close()
			resultCh <- sessionInitResult{err: fmt.Errorf("ssh stdin failed: %w", err)}
			return
		}
		stdout, err := sshSession.StdoutPipe()
		if err != nil {
			_ = sshSession.Close()
			resultCh <- sessionInitResult{err: fmt.Errorf("ssh stdout failed: %w", err)}
			return
		}
		stderr, err := sshSession.StderrPipe()
		if err != nil {
			_ = sshSession.Close()
			resultCh <- sessionInitResult{err: fmt.Errorf("ssh stderr failed: %w", err)}
			return
		}

		if err := sshSession.RequestPty("xterm-256color", rows, cols, ssh.TerminalModes{
			ssh.ECHO:          1,
			ssh.TTY_OP_ISPEED: 14400,
			ssh.TTY_OP_OSPEED: 14400,
		}); err != nil {
			_ = sshSession.Close()
			resultCh <- sessionInitResult{err: fmt.Errorf("ssh pty request failed: %w", err)}
			return
		}
		if strings.TrimSpace(startCommand) != "" {
			if err := sshSession.Start(startCommand); err != nil {
				_ = sshSession.Close()
				resultCh <- sessionInitResult{err: fmt.Errorf("ssh command start failed: %w", err)}
				return
			}
		} else {
			if err := sshSession.Shell(); err != nil {
				_ = sshSession.Close()
				resultCh <- sessionInitResult{err: fmt.Errorf("ssh shell start failed: %w", err)}
				return
			}
		}

		resultCh <- sessionInitResult{
			session: sshSession,
			stdin:   stdin,
			stdout:  stdout,
			stderr:  stderr,
		}
	}()

	if timeout <= 0 {
		result := <-resultCh
		return result.session, result.stdin, result.stdout, result.stderr, result.err
	}

	select {
	case result := <-resultCh:
		return result.session, result.stdin, result.stdout, result.stderr, result.err
	case <-time.After(timeout):
		if sshClient != nil {
			_ = sshClient.Close()
		}
		go func() {
			if r := <-resultCh; r.session != nil {
				_ = r.session.Close()
			}
		}()
		return nil, nil, nil, nil, fmt.Errorf("ssh shell startup timed out after %s", timeout.Round(time.Second))
	}
}

// scrollbackTeeWriter writes terminal output to both the WebSocket and a ring buffer.
type scrollbackTeeWriter struct {
	wsWriter io.Writer
	ringBuf  *terminal.RingBuffer
}

func (tw *scrollbackTeeWriter) Write(p []byte) (int, error) {
	tw.ringBuf.Write(p)
	return tw.wsWriter.Write(p)
}

// scrollbackFlushLoop periodically snapshots the ring buffer and persists it
// to Postgres. It runs until the context is cancelled.
func (d *Deps) scrollbackFlushLoop(ctx context.Context, persistentSessionID string, ringBuf *terminal.RingBuffer) {
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ticker.C:
			if d.TerminalScrollbackStore == nil {
				continue
			}
			snap := ringBuf.Snapshot()
			if len(snap) > 0 {
				_ = d.TerminalScrollbackStore.UpsertScrollback(persistentSessionID, snap, ringBuf.ByteSize(), ringBuf.Lines())
			}
		case <-ctx.Done():
			return
		}
	}
}

// replayScrollbackOnReconnect loads persisted scrollback and optionally merges
// it with a live tmux capture-pane, then sends the result to the browser.
// All errors are non-fatal — reconnect proceeds even if replay fails.
func (d *Deps) replayScrollbackOnReconnect(wsConn *websocket.Conn, sshClient *ssh.Client, session terminal.Session, logContext string) {
	persistentSessionID := strings.TrimSpace(session.PersistentSessionID)
	if persistentSessionID == "" {
		return
	}

	// Load stored scrollback from Postgres.
	var stored []byte
	if d.TerminalScrollbackStore != nil {
		var err error
		stored, err = d.TerminalScrollbackStore.GetScrollback(persistentSessionID)
		if err != nil {
			log.Printf("terminal-ssh: scrollback_replay_skip reason=db_read_failed %s err=%v", logContext, err) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
		}
	}

	// Attempt tmux capture-pane via a non-interactive SSH exec (best-effort).
	var tmuxCapture []byte
	tmuxSessionName := strings.TrimSpace(session.TmuxSessionName)
	if tmuxSessionName != "" && sshClient != nil {
		captureCmd := "tmux capture-pane -t " + shared.ShellSingleQuote(tmuxSessionName) + " -p -e -S -20000 2>/dev/null || true"
		execSession, execErr := sshClient.NewSession()
		if execErr == nil {
			out, runErr := execSession.CombinedOutput(captureCmd)
			_ = execSession.Close()
			if runErr == nil && len(out) > 0 {
				tmuxCapture = out
			}
		}
	}

	// Merge and send.
	merged := terminal.MergeScrollback(stored, tmuxCapture)
	if len(merged) == 0 {
		return
	}
	if err := wsConn.WriteMessage(websocket.BinaryMessage, merged); err != nil {
		log.Printf("terminal-ssh: scrollback_replay_failed reason=ws_write %s err=%v", logContext, err) // #nosec G706 -- Log fields are bounded session/runtime identifiers and local websocket errors.
	} else {
		log.Printf("terminal-ssh: scrollback_replayed %s bytes=%d", logContext, len(merged)) // #nosec G706 -- Log context is composed from bounded session/runtime identifiers.
	}
}

type WriterFunc func([]byte) error

func (w WriterFunc) Write(payload []byte) (int, error) {
	if len(payload) == 0 {
		return 0, nil
	}
	clone := make([]byte, len(payload))
	copy(clone, payload)
	if err := w(clone); err != nil {
		return 0, err
	}
	return len(payload), nil
}

func HandleTerminalControlMessage(sshSession *ssh.Session, stdin io.Writer, payload []byte) (bool, error) {
	if sshSession == nil || len(payload) == 0 {
		return false, nil
	}
	if trimmed := strings.TrimSpace(string(payload)); trimmed == "" || trimmed[0] != '{' {
		return false, nil
	}

	msg := TerminalControlMessage{}
	if err := json.Unmarshal(payload, &msg); err != nil {
		return false, nil
	}

	switch strings.ToLower(strings.TrimSpace(msg.Type)) {
	case "input":
		if msg.Data == "" {
			return true, nil
		}
		_, err := io.WriteString(stdin, msg.Data)
		return true, err
	case "resize":
		cols := msg.Cols
		rows := msg.Rows
		if cols <= 0 {
			cols = 160
		}
		if rows <= 0 {
			rows = 40
		}
		return true, sshSession.WindowChange(rows, cols)
	case "ping":
		return true, nil
	default:
		return false, nil
	}
}
