package topology

import (
	"fmt"
	"regexp"
	"strings"
)

// infraHostTypes is the set of asset types considered infrastructure hosts.
// Assets with these types get their own zone when they have no explicit group.
var infraHostTypes = map[string]bool{
	"host":               true,
	"server":             true,
	"hypervisor":         true,
	"hypervisor-node":    true,
	"nas":               true,
	"container-host":    true,
	"storage-controller": true,
	// NOTE: connector-cluster is intentionally excluded — it's an internal
	// connector asset, not a user-facing infrastructure host. The frontend
	// taxonomy treats it as hidden (HIDDEN_TYPES) and the hierarchy builder
	// classifies it as a child, so giving it its own zone creates empty zones.
}

func isInfraHostType(assetType string) bool {
	return infraHostTypes[strings.ToLower(strings.TrimSpace(assetType))]
}

// zoneColorPalette defines the rotating color set for auto-seeded zones.
var zoneColorPalette = []string{"blue", "green", "purple", "amber", "rose", "cyan"}

// zoneAutoSize computes a zone Size based on member count, using a 2-column grid.
func zoneAutoSize(memberCount int) Size {
	const (
		cardW   = 280.0
		cardH   = 56.0
		padding = 40.0
		header  = 36.0
	)
	cols := memberCount
	if cols > 2 {
		cols = 2
	}
	rows := (memberCount + 1) / 2
	if rows < 1 {
		rows = 1
	}
	w := float64(cols)*cardW + padding
	h := header + float64(rows)*cardH + padding
	if w < 300 {
		w = 300
	}
	if h < 120 {
		h = 120
	}
	return Size{Width: w, Height: h}
}

// AssetInfo is the minimal asset data needed for topology operations.
type AssetInfo struct {
	ID     string
	Label  string // display name, used for zone labeling in seed logic
	Source string // e.g. "Proxmox", "Docker", "TrueNAS"
	Type   string // e.g. "host", "vm", "container", "sensor"
}

// SeedInput contains the data needed to auto-seed a new topology.
type SeedInput struct {
	TopologyID  string
	Assets      []AssetInfo
	Groups      map[string]string // groupID → groupLabel
	AssetGroups map[string]string // assetID → groupID
	Edges       []EdgeInfo        // explicit edges to import as connections
}

// EdgeInfo describes an explicit edge to import as a connection.
type EdgeInfo struct {
	SourceAssetID string
	TargetAssetID string
	Relationship  string
}

// SeedResult contains the zones and members generated by auto-seed.
type SeedResult struct {
	Zones       []Zone
	Members     []ZoneMember
	Connections []Connection
}

// zoneGridPosition returns the top-left position for the nth zone (0-indexed)
// arranged in a grid with at most 3 zones per row.
func zoneGridPosition(index int) Position {
	const (
		colSpacing = 680.0 // wider than max zone width (600px + 80px gap)
		rowSpacing = 350.0
		zonesPerRow = 3
	)
	col := index % zonesPerRow
	row := index / zonesPerRow
	return Position{
		X: float64(col) * colSpacing,
		Y: float64(row) * rowSpacing,
	}
}

// memberGridPosition returns the position of the nth member (0-indexed) within
// a zone, laid out in a simple grid starting at (20, 60) with 280px card width
// and 20px padding.
func memberGridPosition(index int) Position {
	const (
		padding      = 20.0
		cardWidth    = 280.0
		cardHeight   = 80.0
		headerOffset = 60.0
		colsPerZone  = 2
	)
	col := index % colsPerZone
	row := index / colsPerZone
	return Position{
		X: padding + float64(col)*(cardWidth+padding),
		Y: headerOffset + float64(row)*(cardHeight+padding),
	}
}

var nonAlphanumRe = regexp.MustCompile(`[^a-z0-9]+`)

func sanitizeLabel(label string) string {
	s := strings.ToLower(label)
	s = nonAlphanumRe.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s
}

// Seed generates initial zones, members, and connections from existing data.
//
// Logic:
//  1. Assets with a group_id → create a zone named after the group label.
//  2. Assets without a group but with a source → create zones by source name.
//  3. Remaining assets → left unsorted (no zone created).
//  4. Assets are placed inside zones with auto-layout positions.
//  5. Explicit edges are imported as connections (user_defined=false).
//     "contains" edges and edges with unknown relationship types are skipped.
func Seed(input SeedInput) SeedResult {
	if len(input.Assets) == 0 && len(input.Edges) == 0 {
		return SeedResult{}
	}

	// counter used to generate unique zone ID suffixes
	counter := 0
	nextZoneID := func(label string) string {
		counter++
		return fmt.Sprintf("seed-zone-%s-%d", sanitizeLabel(label), counter)
	}

	// zonesByKey maps a stable key (e.g. groupID or "source:Proxmox") to a Zone.
	type zoneEntry struct {
		zone    Zone
		members []AssetInfo
	}
	// Use a slice to preserve insertion order (so grid layout is deterministic).
	zoneIndex := map[string]*zoneEntry{}
	var zoneOrder []string

	colorIdx := 0
	getOrCreateZone := func(key, label string) *zoneEntry {
		if e, ok := zoneIndex[key]; ok {
			return e
		}
		color := zoneColorPalette[colorIdx%len(zoneColorPalette)]
		colorIdx++
		e := &zoneEntry{
			zone: Zone{
				ID:         nextZoneID(label),
				TopologyID: input.TopologyID,
				Label:      label,
				Color:      color,
				Size:       Size{Width: 640, Height: 300},
			},
		}
		zoneIndex[key] = e
		zoneOrder = append(zoneOrder, key)
		return e
	}

	// Build a parent map from "contains" edges so we can group children under
	// host-type parents.  parentMap: childID → parentID.
	parentMap := make(map[string]string)
	for _, edge := range input.Edges {
		if edge.Relationship == "contains" {
			parentMap[edge.TargetAssetID] = edge.SourceAssetID
		}
	}

	// Build a set of asset IDs for quick lookup.
	assetByIDMap := make(map[string]AssetInfo, len(input.Assets))
	for _, a := range input.Assets {
		assetByIDMap[a.ID] = a
	}

	// First pass: assets with explicit groups (highest priority).
	groupedAssets := make(map[string]bool)
	for _, asset := range input.Assets {
		if groupID, ok := input.AssetGroups[asset.ID]; ok && groupID != "" {
			label := input.Groups[groupID]
			if label == "" {
				label = groupID
			}
			e := getOrCreateZone("group:"+groupID, label)
			e.members = append(e.members, asset)
			groupedAssets[asset.ID] = true
		}
	}

	// Second pass: infra host assets (no group) → each gets its own zone.
	hostZoneAssets := make(map[string]string) // assetID → zone key
	for _, asset := range input.Assets {
		if groupedAssets[asset.ID] {
			continue
		}
		if isInfraHostType(asset.Type) {
			key := "host:" + asset.ID
			label := asset.Label
			if label == "" {
				label = asset.ID
			}
			e := getOrCreateZone(key, label)
			e.members = append(e.members, asset)
			hostZoneAssets[asset.ID] = key
		}
	}

	// Third pass: non-host, non-grouped assets → check contains edges for parent host zone,
	// otherwise fall back to source-based grouping.
	for _, asset := range input.Assets {
		if groupedAssets[asset.ID] {
			continue
		}
		if hostZoneAssets[asset.ID] != "" {
			continue
		}
		// Check if this asset has a parent host that owns a zone.
		if parentID, ok := parentMap[asset.ID]; ok {
			if hostKey, hasZone := hostZoneAssets[parentID]; hasZone {
				e := zoneIndex[hostKey]
				e.members = append(e.members, asset)
				continue
			}
		}
		// Fall back to source-based zone.
		if asset.Source != "" {
			e := getOrCreateZone("source:"+asset.Source, asset.Source)
			e.members = append(e.members, asset)
			continue
		}
		// No group, no host parent, no source → unsorted, skip.
	}

	// Assign grid positions to zones and members; auto-size zones.
	// Size zones based on the count of host-type members only, since the
	// frontend hides child members inside their parent's ContainmentCard.
	var zones []Zone
	var members []ZoneMember

	for i, key := range zoneOrder {
		e := zoneIndex[key]
		e.zone.SortOrder = i
		e.zone.Position = zoneGridPosition(i)
		topLevelCount := 0
		for _, m := range e.members {
			_, hasParent := parentMap[m.ID]
			if !hasParent || isInfraHostType(m.Type) {
				topLevelCount++
			}
		}
		if topLevelCount == 0 {
			topLevelCount = 1 // at least 1 for minimum zone sizing
		}
		e.zone.Size = zoneAutoSize(topLevelCount)
		zones = append(zones, e.zone)

		for j, asset := range e.members {
			members = append(members, ZoneMember{
				ZoneID:    e.zone.ID,
				AssetID:   asset.ID,
				Position:  memberGridPosition(j),
				SortOrder: j,
			})
		}
	}

	// Import explicit edges as connections (skip "contains", skip unknown types).
	var connections []Connection
	connCounter := 0
	for _, edge := range input.Edges {
		if edge.Relationship == "contains" {
			continue
		}
		if !ValidRelationships[edge.Relationship] {
			continue
		}
		connCounter++
		connections = append(connections, Connection{
			ID:            fmt.Sprintf("seed-conn-%d", connCounter),
			TopologyID:    input.TopologyID,
			SourceAssetID: edge.SourceAssetID,
			TargetAssetID: edge.TargetAssetID,
			Relationship:  edge.Relationship,
			UserDefined:   false,
		})
	}

	return SeedResult{
		Zones:       zones,
		Members:     members,
		Connections: connections,
	}
}
