package persistence

// Migration guidelines:
//
// 1. Always add migrations at the END of the slice — never modify existing ones.
// 2. Use IF NOT EXISTS / IF EXISTS for idempotency.
// 3. Each migration runs in a single transaction — all statements succeed or all fail.
// 4. Test migrations on a copy of production data before deploying.
// 5. Rollback is via database restore — see docs/internal/UPGRADING.md.
// 6. Advisory locks prevent concurrent migration races.

func postgresSchemaMigrations() []schemaMigration {
	return []schemaMigration{
		schemaMigrationCoreSchema(),
		schemaMigrationRetentionSettings(),
		schemaMigrationSitesAndAssetSiteFk(),
		schemaMigrationRuntimeSettings(),
		schemaMigrationSiteGeoAndMaintenanceWindows(),
		schemaMigrationTerminalCredentialsAndAssetTerminalConfig(),
		schemaMigrationAlertingRulesTargetsEvaluations(),
		schemaMigrationIncidentsAndAlertLinks(),
		schemaMigrationJobQueue(),
		schemaMigrationAuthUsersSessions(),
		schemaMigrationAlertInstancesSilences(),
		schemaMigrationNotificationChannelsRoutesHistory(),
		schemaMigrationAssetDependenciesIncidentAssets(),
		schemaMigrationSyntheticChecksReliabilityHistoryMaintenanceOverrides(),
		schemaMigrationIncidentEvents(),
		schemaMigrationSiteProfilesFailoverPairs(),
		schemaMigrationHubCollectors(),
		schemaMigrationIncidentPostmortem(),
		schemaMigrationEnrollmentAndAgentTokens(),
		schemaMigrationAgentPresence(),
		schemaMigrationAssetDesktopConfigs(),
		schemaMigrationHubCollectorsAddProxmox(),
		schemaMigrationNoopSequencePlaceholder(),
		schemaMigrationHubCollectorsAddTruenas(),
		schemaMigrationHubCollectorsAddPortainerDocker(),
		schemaMigrationHubCollectorsAddPbs(),
		schemaMigrationHubCollectorsAddHomeassistant(),
		schemaMigrationCanonicalModelPersistence(),
		schemaMigrationAssetTags(),
		schemaMigrationAgentTokensExpiry(),
		schemaMigrationNormalizeAgentSource(),
		schemaMigrationAddHostedOnRelationshipType(),
		schemaMigrationNotificationHistoryRetryColumns(),
		schemaMigrationTerminalUplift(),
		schemaMigrationSessionRecordings(),
		schemaMigrationWebServicesManualAndOverrides(),
		schemaMigrationPushDevices(),
		schemaMigrationLogEventsSourceLevelTimestampIndex(),
		schemaMigrationLogEventsDeadLetterErrorTimestampIndex(),
		schemaMigrationLogEventsTimestampSourceIndex(),
		schemaMigrationLogEventsSiteProjectionTimestampIndex(),
		schemaMigrationAuthRolesAndOidcIdentity(),
		schemaMigrationWebServiceOverridesTags(),
		schemaMigrationWebServiceAltUrlsAndGrouping(),
		schemaMigrationMigrateMergeSettingsToUrlGrouping(),
		schemaMigrationGroupsTableAndSiteMigration(),
		schemaMigrationTerminalPersistentSessions(),
		schemaMigrationTotpColumns(),
		schemaMigrationGroupsSiteCompatibilityRestore(),
		schemaMigrationGroupIdSiteCompatibilityRepair(),
		schemaMigrationGroupIdForeignKeyRetargeting(),
		schemaMigrationGroupColumnsCanonicalization(),
		schemaMigrationGroupTableAndFilterCanonicalization(),
		schemaMigrationGroupTableAndFilterRenames(),
		schemaMigrationSystemSettings(),
		schemaMigrationAddManualDeviceProtocolConfigs(),
		schemaMigrationGroupsJumpChain(),
		schemaMigrationWorkspaceTabPanelSizes(),
		schemaMigrationWebServicesManualNullableHost(),
		schemaMigrationRenameAssetDependenciesToAssetEdgesAndAddComposites(),
		schemaMigrationMigrateLinkSuggestionsToEdgeProposals(),
		schemaMigrationTerminalSessionBookmarksAndScrollback(),
		schemaMigrationFileConnectionsAndTransfers(),
		schemaMigrationMetricSamplesLabels(),
		schemaMigrationApiKeys(),
		schemaMigrationWebhooks(),
		schemaMigrationScheduledTasks(),
		schemaMigrationSavedActions(),
		schemaMigrationMigrateLegacyConfigsToProtocolConfigs(),
		schemaMigrationAddSyntheticCheckServiceLink(),
		schemaMigrationTopologyCanvas(),
		schemaMigrationRemoteBookmarks(),
		schemaMigrationAuditEventsIndexes(),
		schemaMigrationNotificationHistoryPayload(),
		schemaMigrationWebhookSecretCiphertext(),
		schemaMigrationSavedLogViewsOwnerScope(),
		schemaMigrationFileTransfersActorScope(),
		schemaMigrationJobQueueLeasesAndBackoff(),
		schemaMigrationSavedActionsOwnerIndex(),
		schemaMigrationFileConnectionsActorScope(),
		schemaMigrationFileConnectionsActorBackfillSingleOwner(),
		schemaMigrationPushDeviceNotificationPreferences(),
		schemaMigrationTerminalUserStateActorScope(),
		schemaMigrationPushDeviceTimezoneAndTokenOwnership(),
		schemaMigrationOidcIssuerScopedIdentity(),
		schemaMigrationPushDeviceTimezoneUnknownDefault(),
		schemaMigrationHubMetricSamples(),
		schemaMigrationMetricSamplesBoundedLabeledSnapshotIndex(),
		schemaMigrationLiveActivityPushTokens(),
		schemaMigrationScheduledTaskExecutionState(),
		schemaMigrationDurablePushAlertDigests(),
		schemaMigrationPreparedAgentApprovalTokens(),
		schemaMigrationDurableAgentIdentityState(),
		schemaMigrationPrometheusRemoteWriteReplayState(),
		schemaMigrationCredentialProfileLifecycleGuards(),
		schemaMigrationHubSyntheticMetricScope(),
		schemaMigrationRetiredAgentIdentities(),
		schemaMigrationScopedEnrollmentTokens(),
		schemaMigrationScrubCollectorUrlUserinfo(),
		schemaMigrationRemoteBookmarkSpiceTransportSecurity(),
		schemaMigrationRemoteBookmarkVncTransportSecurity(),
	}
}
