package agentmgr

// Re-export protocol types and constants for backward compatibility.
// The source of truth is github.com/labtether/protocol.

import "github.com/labtether/protocol"

type Message = protocol.Message
type HeartbeatData = protocol.HeartbeatData
type ConnectorInfo = protocol.ConnectorInfo
type TelemetryData = protocol.TelemetryData
type CommandRequestData = protocol.CommandRequestData
type CommandResultData = protocol.CommandResultData
type LogStreamData = protocol.LogStreamData
type LogBatchData = protocol.LogBatchData
type JournalQueryData = protocol.JournalQueryData
type JournalEntriesData = protocol.JournalEntriesData
type ConfigUpdateData = protocol.ConfigUpdateData
type ConfigAppliedData = protocol.ConfigAppliedData
type AgentSettingsApplyData = protocol.AgentSettingsApplyData
type AgentSettingsAppliedData = protocol.AgentSettingsAppliedData
type AgentSettingsStateData = protocol.AgentSettingsStateData
type UpdateRequestData = protocol.UpdateRequestData
type UpdateProgressData = protocol.UpdateProgressData
type UpdateResultData = protocol.UpdateResultData
type TerminalProbeResponse = protocol.TerminalProbeResponse
type TerminalStartData = protocol.TerminalStartData
type TerminalStartedData = protocol.TerminalStartedData
type TerminalDataPayload = protocol.TerminalDataPayload
type TerminalResizeData = protocol.TerminalResizeData
type TerminalTmuxKillData = protocol.TerminalTmuxKillData
type TerminalCloseData = protocol.TerminalCloseData
type SSHKeyInstallData = protocol.SSHKeyInstallData
type SSHKeyRemoveData = protocol.SSHKeyRemoveData
type SSHKeyInstalledData = protocol.SSHKeyInstalledData
type DesktopStartData = protocol.DesktopStartData
type DesktopStartedData = protocol.DesktopStartedData
type DesktopDataPayload = protocol.DesktopDataPayload
type DesktopCloseData = protocol.DesktopCloseData
type WebRTCCapabilitiesData = protocol.WebRTCCapabilitiesData
type WebRTCSessionData = protocol.WebRTCSessionData
type WebRTCSDPData = protocol.WebRTCSDPData
type WebRTCICEData = protocol.WebRTCICEData
type WebRTCStartedData = protocol.WebRTCStartedData
type WebRTCStoppedData = protocol.WebRTCStoppedData
type WebRTCInputData = protocol.WebRTCInputData
type ClipboardGetData = protocol.ClipboardGetData
type ClipboardDataPayload = protocol.ClipboardDataPayload
type ClipboardSetData = protocol.ClipboardSetData
type ClipboardSetAckData = protocol.ClipboardSetAckData
type DesktopAudioStartData = protocol.DesktopAudioStartData
type DesktopAudioStopData = protocol.DesktopAudioStopData
type DesktopAudioDataPayload = protocol.DesktopAudioDataPayload
type DesktopAudioStateData = protocol.DesktopAudioStateData
type DisplayInfo = protocol.DisplayInfo
type DisplayListData = protocol.DisplayListData
type DesktopDiagnosticRequest = protocol.DesktopDiagnosticRequest
type DesktopDiagnosticData = protocol.DesktopDiagnosticData
type WoLSendData = protocol.WoLSendData
type WoLResultData = protocol.WoLResultData
type FileListData = protocol.FileListData
type FileEntry = protocol.FileEntry
type FileListedData = protocol.FileListedData
type FileReadData = protocol.FileReadData
type FileDataPayload = protocol.FileDataPayload
type FileWriteData = protocol.FileWriteData
type FileWrittenData = protocol.FileWrittenData
type FileMkdirData = protocol.FileMkdirData
type FileDeleteData = protocol.FileDeleteData
type FileRenameData = protocol.FileRenameData
type FileCopyData = protocol.FileCopyData
type FileResultData = protocol.FileResultData
type FileSearchData = protocol.FileSearchData
type FileSearchResultData = protocol.FileSearchResultData
type AlertNotifyData = protocol.AlertNotifyData
type EnrollmentApprovedData = protocol.EnrollmentApprovedData
type EnrollmentChallengeData = protocol.EnrollmentChallengeData
type EnrollmentProofData = protocol.EnrollmentProofData
type EnrollmentRejectedData = protocol.EnrollmentRejectedData
type DockerEngineInfo = protocol.DockerEngineInfo
type DockerPortMapping = protocol.DockerPortMapping
type DockerMountInfo = protocol.DockerMountInfo
type DockerContainerInfo = protocol.DockerContainerInfo
type DockerImageInfo = protocol.DockerImageInfo
type DockerNetworkInfo = protocol.DockerNetworkInfo
type DockerVolumeInfo = protocol.DockerVolumeInfo
type DockerComposeStack = protocol.DockerComposeStack
type DockerDiscoveryData = protocol.DockerDiscoveryData
type DockerDiscoveryDeltaData = protocol.DockerDiscoveryDeltaData
type DockerContainerStats = protocol.DockerContainerStats
type DockerStatsData = protocol.DockerStatsData
type DockerEventActor = protocol.DockerEventActor
type DockerEventData = protocol.DockerEventData
type DockerActionData = protocol.DockerActionData
type DockerActionResultData = protocol.DockerActionResultData
type DockerLogsStartData = protocol.DockerLogsStartData
type DockerLogsStopData = protocol.DockerLogsStopData
type DockerLogsStreamData = protocol.DockerLogsStreamData
type DockerExecStartData = protocol.DockerExecStartData
type DockerExecStartedData = protocol.DockerExecStartedData
type DockerExecDataPayload = protocol.DockerExecDataPayload
type DockerExecInputData = protocol.DockerExecInputData
type DockerExecResizeData = protocol.DockerExecResizeData
type DockerExecCloseData = protocol.DockerExecCloseData
type DockerComposeActionData = protocol.DockerComposeActionData
type DockerComposeResultData = protocol.DockerComposeResultData
type ProcessListData = protocol.ProcessListData
type ProcessListedData = protocol.ProcessListedData
type ProcessInfo = protocol.ProcessInfo
type ProcessKillData = protocol.ProcessKillData
type ProcessKillResultData = protocol.ProcessKillResultData
type ServiceListData = protocol.ServiceListData
type ServiceListedData = protocol.ServiceListedData
type ServiceInfo = protocol.ServiceInfo
type ServiceActionData = protocol.ServiceActionData
type ServiceResultData = protocol.ServiceResultData
type DiskListData = protocol.DiskListData
type DiskListedData = protocol.DiskListedData
type MountInfo = protocol.MountInfo
type NetworkListData = protocol.NetworkListData
type NetworkListedData = protocol.NetworkListedData
type NetInterface = protocol.NetInterface
type NetworkActionData = protocol.NetworkActionData
type NetworkResultData = protocol.NetworkResultData
type PackageListData = protocol.PackageListData
type PackageListedData = protocol.PackageListedData
type PackageInfo = protocol.PackageInfo
type PackageActionData = protocol.PackageActionData
type PackageResultData = protocol.PackageResultData
type CronListData = protocol.CronListData
type CronListedData = protocol.CronListedData
type CronEntry = protocol.CronEntry
type UsersListData = protocol.UsersListData
type UsersListedData = protocol.UsersListedData
type UserSession = protocol.UserSession
type WebServiceReportData = protocol.WebServiceReportData
type WebServiceDiscoveryStats = protocol.WebServiceDiscoveryStats
type WebServiceDiscoverySourceStat = protocol.WebServiceDiscoverySourceStat
type WebServiceHealthPoint = protocol.WebServiceHealthPoint
type WebServiceHealthSummary = protocol.WebServiceHealthSummary
type DiscoveredWebService = protocol.DiscoveredWebService

const (
	MsgHeartbeat = protocol.MsgHeartbeat
	MsgTelemetry = protocol.MsgTelemetry
	MsgCommandRequest = protocol.MsgCommandRequest
	MsgCommandResult = protocol.MsgCommandResult
	MsgPing = protocol.MsgPing
	MsgPong = protocol.MsgPong
	MsgLogStream = protocol.MsgLogStream
	MsgLogBatch = protocol.MsgLogBatch
	MsgJournalQuery = protocol.MsgJournalQuery
	MsgJournalEntries = protocol.MsgJournalEntries
	MsgConfigUpdate = protocol.MsgConfigUpdate
	MsgConfigApplied = protocol.MsgConfigApplied
	MsgAgentSettingsApply = protocol.MsgAgentSettingsApply
	MsgAgentSettingsApplied = protocol.MsgAgentSettingsApplied
	MsgAgentSettingsState = protocol.MsgAgentSettingsState
	MsgUpdateRequest = protocol.MsgUpdateRequest
	MsgUpdateProgress = protocol.MsgUpdateProgress
	MsgUpdateResult = protocol.MsgUpdateResult
	MsgTerminalProbe = protocol.MsgTerminalProbe
	MsgTerminalProbed = protocol.MsgTerminalProbed
	MsgTerminalStart = protocol.MsgTerminalStart
	MsgTerminalStarted = protocol.MsgTerminalStarted
	MsgTerminalData = protocol.MsgTerminalData
	MsgTerminalResize = protocol.MsgTerminalResize
	MsgTerminalTmuxKill = protocol.MsgTerminalTmuxKill
	MsgTerminalClose = protocol.MsgTerminalClose
	MsgTerminalClosed = protocol.MsgTerminalClosed
	MsgSSHKeyInstall = protocol.MsgSSHKeyInstall
	MsgSSHKeyInstalled = protocol.MsgSSHKeyInstalled
	MsgSSHKeyRemove = protocol.MsgSSHKeyRemove
	MsgSSHKeyRemoved = protocol.MsgSSHKeyRemoved
	MsgDesktopStart = protocol.MsgDesktopStart
	MsgDesktopStarted = protocol.MsgDesktopStarted
	MsgDesktopData = protocol.MsgDesktopData
	MsgDesktopClose = protocol.MsgDesktopClose
	MsgDesktopClosed = protocol.MsgDesktopClosed
	MsgDesktopListDisplays = protocol.MsgDesktopListDisplays
	MsgDesktopDisplays = protocol.MsgDesktopDisplays
	MsgDesktopDiagnose = protocol.MsgDesktopDiagnose
	MsgDesktopDiagnosed = protocol.MsgDesktopDiagnosed
	MsgWebRTCCapabilities = protocol.MsgWebRTCCapabilities
	MsgWebRTCOffer = protocol.MsgWebRTCOffer
	MsgWebRTCAnswer = protocol.MsgWebRTCAnswer
	MsgWebRTCICE = protocol.MsgWebRTCICE
	MsgWebRTCStart = protocol.MsgWebRTCStart
	MsgWebRTCStarted = protocol.MsgWebRTCStarted
	MsgWebRTCStop = protocol.MsgWebRTCStop
	MsgWebRTCStopped = protocol.MsgWebRTCStopped
	MsgWebRTCInput = protocol.MsgWebRTCInput
	MsgClipboardGet = protocol.MsgClipboardGet
	MsgClipboardData = protocol.MsgClipboardData
	MsgClipboardSet = protocol.MsgClipboardSet
	MsgClipboardSetAck = protocol.MsgClipboardSetAck
	MsgDesktopAudioStart = protocol.MsgDesktopAudioStart
	MsgDesktopAudioStop = protocol.MsgDesktopAudioStop
	MsgDesktopAudioData = protocol.MsgDesktopAudioData
	MsgDesktopAudioState = protocol.MsgDesktopAudioState
	MsgWoLSend = protocol.MsgWoLSend
	MsgWoLResult = protocol.MsgWoLResult
	MsgFileList = protocol.MsgFileList
	MsgFileListed = protocol.MsgFileListed
	MsgFileRead = protocol.MsgFileRead
	MsgFileData = protocol.MsgFileData
	MsgFileWrite = protocol.MsgFileWrite
	MsgFileWritten = protocol.MsgFileWritten
	MsgFileMkdir = protocol.MsgFileMkdir
	MsgFileDelete = protocol.MsgFileDelete
	MsgFileRename = protocol.MsgFileRename
	MsgFileCopy = protocol.MsgFileCopy
	MsgFileResult = protocol.MsgFileResult
	MsgFileSearch = protocol.MsgFileSearch
	MsgFileSearchResult = protocol.MsgFileSearchResult
	MsgProcessList = protocol.MsgProcessList
	MsgProcessListed = protocol.MsgProcessListed
	MsgProcessKill = protocol.MsgProcessKill
	MsgProcessKillResult = protocol.MsgProcessKillResult
	MsgServiceList = protocol.MsgServiceList
	MsgServiceListed = protocol.MsgServiceListed
	MsgServiceAction = protocol.MsgServiceAction
	MsgServiceResult = protocol.MsgServiceResult
	MsgDiskList = protocol.MsgDiskList
	MsgDiskListed = protocol.MsgDiskListed
	MsgNetworkList = protocol.MsgNetworkList
	MsgNetworkListed = protocol.MsgNetworkListed
	MsgNetworkAction = protocol.MsgNetworkAction
	MsgNetworkResult = protocol.MsgNetworkResult
	MsgPackageList = protocol.MsgPackageList
	MsgPackageListed = protocol.MsgPackageListed
	MsgPackageAction = protocol.MsgPackageAction
	MsgPackageResult = protocol.MsgPackageResult
	MsgCronList = protocol.MsgCronList
	MsgCronListed = protocol.MsgCronListed
	MsgUsersList = protocol.MsgUsersList
	MsgUsersListed = protocol.MsgUsersListed
	MsgAlertNotify = protocol.MsgAlertNotify
	MsgEnrollmentChallenge = protocol.MsgEnrollmentChallenge
	MsgEnrollmentProof = protocol.MsgEnrollmentProof
	MsgEnrollmentApproved = protocol.MsgEnrollmentApproved
	MsgEnrollmentRejected = protocol.MsgEnrollmentRejected
	MsgDockerDiscovery = protocol.MsgDockerDiscovery
	MsgDockerDiscoveryDelta = protocol.MsgDockerDiscoveryDelta
	MsgDockerStats = protocol.MsgDockerStats
	MsgDockerEvents = protocol.MsgDockerEvents
	MsgDockerAction = protocol.MsgDockerAction
	MsgDockerActionResult = protocol.MsgDockerActionResult
	MsgDockerLogsStart = protocol.MsgDockerLogsStart
	MsgDockerLogsStop = protocol.MsgDockerLogsStop
	MsgDockerLogsStream = protocol.MsgDockerLogsStream
	MsgDockerExecStart = protocol.MsgDockerExecStart
	MsgDockerExecStarted = protocol.MsgDockerExecStarted
	MsgDockerExecData = protocol.MsgDockerExecData
	MsgDockerExecInput = protocol.MsgDockerExecInput
	MsgDockerExecResize = protocol.MsgDockerExecResize
	MsgDockerExecClose = protocol.MsgDockerExecClose
	MsgDockerExecClosed = protocol.MsgDockerExecClosed
	MsgDockerComposeAction = protocol.MsgDockerComposeAction
	MsgDockerComposeResult = protocol.MsgDockerComposeResult
	MsgWebServiceReport = protocol.MsgWebServiceReport
	MsgWebServiceSync = protocol.MsgWebServiceSync
)
